# Generated by Django 4.2.30 on 2026-09-25 05:08

import deca.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conductor DeCA',
                'verbose_name_plural': 'Conductores DeCA',
                'db_table': 'deca_conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionDeca',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol_habitual', models.CharField(choices=[('cargador', 'Cargador (expide la mercancía)'), ('transportista', 'Transportista (realiza el transporte)')], default='cargador', help_text='Papel que juega normalmente esta empresa en sus expediciones. Decide qué campo se precarga con su propio NIF y cómo se reparten los NIF que lee la extracción automática. Siempre se puede corregir a mano en una expedición concreta.', max_length=20)),
                ('canal_notificacion_conductor', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('notificar_cliente_activo', models.BooleanField(default=False)),
                ('canal_notificacion_cliente', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('notificar_transportista_activo', models.BooleanField(default=False)),
                ('canal_notificacion_transportista', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('dias_visibilidad_publica', models.PositiveIntegerField(default=10, help_text='Días que la URL pública del QR permite descarga sin login tras finalizar el transporte. Suelo legal: 7 días (Orden FOM/2861/2012 y Resolución de 5-jun-2026) -- no se puede configurar por debajo.', validators=[django.core.validators.MinValueValidator(7)])),
                ('dias_retencion_ip_eventos', models.PositiveIntegerField(default=365, help_text='Días que se conserva la IP de origen de un evento de auditoría (ej. descarga pública por QR) antes de anonimizarla. No es un requisito de la norma DeCA -- es minimización de datos RGPD; por defecto se alinea con la custodia legal de 1 año del propio DeCA. El resto del evento (tipo, fecha, hash) nunca se borra.')),
                ('informe_mostrar_cabecera', models.BooleanField(default=False)),
                ('informe_codigo_documento', models.CharField(blank=True, max_length=50)),
                ('informe_version', models.CharField(blank=True, max_length=20)),
                ('informe_edicion', models.CharField(blank=True, max_length=20)),
                ('informe_preparado_por', models.CharField(blank=True, max_length=100)),
                ('informe_autorizado_por', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Configuración de DeCA',
                'verbose_name_plural': 'Configuración de DeCA',
                'db_table': 'deca_configuracion',
            },
        ),
        migrations.CreateModel(
            name='DestinatarioDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destinatario DeCA',
                'verbose_name_plural': 'Destinatarios DeCA',
                'db_table': 'deca_destinatarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaTransportistaDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa transportista DeCA',
                'verbose_name_plural': 'Empresas transportistas DeCA',
                'db_table': 'deca_empresas_transportistas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ExpedicionDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('generado', 'Generado'), ('anulado', 'Anulado')], default='borrador', max_length=20)),
                ('numero_albaran', models.CharField(blank=True, help_text='Número de albarán/expedición tal como lo maneja el cliente (texto libre, no es la PK).', max_length=100)),
                ('numero_cmr', models.CharField(blank=True, help_text='Número propio de la carta de porte CMR (esquina superior derecha del documento, ej. "00000019.300"), distinto del número de albarán -- solo aplica cuando el transporte va acompañado de CMR.', max_length=100)),
                ('anio', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('nif_cargador', models.CharField(blank=True, max_length=20)),
                ('nombre_cargador', models.CharField(blank=True, max_length=255)),
                ('nif_transportista', models.CharField(blank=True, max_length=20)),
                ('nombre_transportista', models.CharField(blank=True, max_length=255)),
                ('nif_destinatario', models.CharField(blank=True, max_length=20)),
                ('nombre_destinatario', models.CharField(blank=True, max_length=255)),
                ('matricula_tractor', models.CharField(blank=True, max_length=15)),
                ('matricula_remolque', models.CharField(blank=True, max_length=15)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('fecha_hora_transporte', models.DateTimeField(blank=True, null=True)),
                ('naturaleza_mercancia', models.CharField(blank=True, max_length=255)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bultos', models.PositiveIntegerField(blank=True, null=True)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('codigo_mercancia', models.CharField(blank=True, help_text='Código UN/ADR u otro código interno de la mercancía, si aplica.', max_length=50)),
                ('numero_pedido', models.CharField(blank=True, max_length=100)),
                ('instrucciones_conductor', models.TextField(blank=True)),
                ('contacto_emergencias', models.CharField(blank=True, max_length=255)),
                ('tipo_contenedor', models.CharField(blank=True, max_length=100)),
                ('instrucciones_expedidor', models.TextField(blank=True)),
                ('instrucciones_pago', models.TextField(blank=True)),
                ('comentarios', models.TextField(blank=True)),
                ('nombre_conductor', models.CharField(blank=True, max_length=255)),
                ('nif_conductor', models.CharField(blank=True, max_length=20)),
                ('telefono_conductor', models.CharField(blank=True, max_length=20)),
                ('email_conductor', models.EmailField(blank=True, max_length=254)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to=deca.models._ruta_pdf_deca)),
                ('hash_sha256', models.CharField(blank=True, help_text='SHA-256 del PDF final generado.', max_length=64)),
                ('fecha_generacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_expiracion_publica', models.DateTimeField(blank=True, help_text='fecha_generacion + dias_visibilidad_publica vigente en ese momento. Pasada esta fecha, el token deja de servir el PDF sin autenticación.', null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediciones_deca_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expedición DeCA',
                'verbose_name_plural': 'Expediciones DeCA',
                'db_table': 'deca_expediciones',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='RemolqueDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Remolque DeCA',
                'verbose_name_plural': 'Remolques DeCA',
                'db_table': 'deca_remolques',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='TractoraDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('alias', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tractora DeCA',
                'verbose_name_plural': 'Tractoras DeCA',
                'db_table': 'deca_tractoras',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='TransportistaSucesivoDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('orden', models.PositiveSmallIntegerField(help_text='Posición en la cadena de subcontratación (1 = el primero tras el transportista efectivo).')),
                ('nif', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('matricula', models.CharField(blank=True, max_length=15)),
                ('expedicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportistas_sucesivos', to='deca.expediciondeca')),
            ],
            options={
                'verbose_name': 'Transportista sucesivo DeCA',
                'verbose_name_plural': 'Transportistas sucesivos DeCA',
                'db_table': 'deca_transportistas_sucesivos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EventoExpedicionDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_evento', models.CharField(choices=[('creada', 'Expedición creada'), ('documento_subido', 'Documento origen subido'), ('vista_previa', 'Vista previa generada'), ('editada', 'Datos editados'), ('confirmada', 'Confirmada'), ('generada', 'DeCA generado'), ('descarga_publica', 'Descarga pública por QR'), ('anulada', 'Anulada'), ('enviada_email', 'Enviada por email')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('hash_documento', models.CharField(blank=True, help_text='hash_sha256 de la expedición en el momento del evento -- permite demostrar qué versión exacta del PDF se sirvió/consultó.', max_length=64)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('expedicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='deca.expediciondeca')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío en eventos sin usuario autenticado (ej. descarga pública por QR).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_deca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de expedición DeCA',
                'verbose_name_plural': 'Eventos de expedición DeCA',
                'db_table': 'deca_eventos_expedicion',
                'ordering': ['fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoOrigenDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('albaran_venta', 'Albarán de venta'), ('cmr', 'CMR'), ('otro', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to=deca.models._ruta_documento_origen)),
                ('nombre_original', models.CharField(max_length=255)),
                ('expedicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_origen', to='deca.expediciondeca')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_origen_deca_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento origen DeCA',
                'verbose_name_plural': 'Documentos origen DeCA',
                'db_table': 'deca_documentos_origen',
                'ordering': ['fecha_alta'],
            },
        ),
        migrations.AddConstraint(
            model_name='transportistasucesivodeca',
            constraint=models.UniqueConstraint(fields=('expedicion', 'orden'), name='deca_transportista_sucesivo_orden_unico'),
        ),
    ]
