# Generated by Django 4.2.30 on 2026-10-01 21:28

import deca.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasAgendaDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('cargador', 'Cargador'), ('transportista', 'Transportista'), ('destinatario', 'Destinatario'), ('conductor', 'Conductor'), ('tractora', 'Tractora'), ('remolque', 'Remolque')], max_length=20)),
                ('texto', models.CharField(max_length=255)),
                ('texto_original', models.CharField(blank=True, max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('nif', models.CharField(blank=True, max_length=20)),
                ('veces_confirmado', models.PositiveIntegerField(default=1)),
                ('ultima_confirmacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sinónimo de la Agenda DeCA',
                'verbose_name_plural': 'Sinónimos de la Agenda DeCA',
                'db_table': 'deca_alias_agenda',
                'ordering': ['rol', 'texto'],
            },
        ),
        migrations.CreateModel(
            name='CargadorDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargador DeCA',
                'verbose_name_plural': 'Cargadores DeCA',
                'db_table': 'deca_cargadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LecturaCampoDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('campo', models.CharField(max_length=50)),
                ('valor_leido', models.TextField(blank=True)),
                ('valor_propuesto', models.TextField(blank=True)),
                ('fuente', models.CharField(choices=[('ia', 'Lectura de la IA'), ('modelo', 'Valor fijo del modelo de documento'), ('agenda', 'Completado desde la Agenda'), ('sinonimo', 'Sinónimo aprendido'), ('correccion', 'Corrección de letras confundidas')], default='ia', max_length=20)),
                ('dudoso', models.BooleanField(default=False, help_text='La IA lo marcó como manuscrito o poco legible.')),
                ('valor_final', models.TextField(blank=True)),
                ('corregido', models.BooleanField(blank=True, help_text='Vacío mientras el DeCA no se genera.', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lectura de campo DeCA',
                'verbose_name_plural': 'Lecturas de campo DeCA',
                'db_table': 'deca_lecturas_campo',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='ModificacionDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField()),
                ('cambios', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Modificación de DeCA generado',
                'verbose_name_plural': 'Modificaciones de DeCA generados',
                'db_table': 'deca_modificaciones',
                'ordering': ['fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumentoDeca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_documento', models.CharField(choices=[('albaran_venta', 'Albarán de venta'), ('cmr', 'CMR'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('texto_identificativo', models.CharField(blank=True, max_length=255)),
                ('instrucciones', models.TextField(blank=True)),
                ('valores_fijos', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
                ('veces_aplicada', models.PositiveIntegerField(default=0)),
                ('ultima_vez_aplicada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Modelo de documento DeCA',
                'verbose_name_plural': 'Modelos de documento DeCA',
                'db_table': 'deca_plantillas_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='agenda_prioritaria',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='aviso_sin_completar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='aviso_sin_completar_dias',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='deca_anticipado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='ejemplares_sin_cobertura',
            field=models.PositiveSmallIntegerField(default=2, help_text='Ejemplares que se imprimen sin cobertura: 1 transportista, 2 + cargador, 3 + destinatario.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='exigir_datos_destinatario',
            field=models.BooleanField(default=False, help_text='Exigir nombre y NIF del destinatario para poder confirmar (la norma no los exige).'),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='horas_max_edicion_generado',
            field=models.PositiveIntegerField(default=24, help_text='Horas desde que se generó el DeCA oficial durante las que se puede seguir corrigiendo un dato sin anular la expedición. Pasado este plazo, queda bloqueada como siempre.'),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='identificador_preferido',
            field=models.CharField(choices=[('numero_albaran', 'Número de albarán'), ('numero_cmr', 'Número de CMR'), ('automatico', 'Contador automático')], default='numero_albaran', help_text='Qué número se usa como referencia de esta empresa en el asunto del email, el nombre del PDF y el título del historial de auditoría. Si el campo elegido está vacío en una expedición concreta, se cae en cascada al siguiente disponible (albarán → CMR → contador automático → id interno), nunca se deja sin nada.', max_length=20),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='modo_sin_cobertura',
            field=models.CharField(choices=[('imprimir', 'Imprimir en el móvil'), ('generar_al_volver', 'Guardar y generar al volver la red'), ('necesita_red', 'Necesita red')], default='imprimir', max_length=20),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='plantilla_asunto_email',
            field=models.CharField(blank=True, help_text='Asunto por defecto del email de envío del DeCA. Vacío = se usa el número de albarán/expedición. Placeholders: {numero_albaran} {origen} {destino} {matricula_tractor} {empresa}.', max_length=200),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='plantilla_cuerpo_email',
            field=models.TextField(blank=True, help_text='Mensaje por defecto del email de envío del DeCA. Vacío = se usa el mensaje estándar. Mismos placeholders que el asunto.'),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='prefijo_numero_automatico',
            field=models.CharField(blank=True, default='DECA-', max_length=20),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='registrar_papel_por_foto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuraciondeca',
            name='ultimo_numero_automatico',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='autorizacion_especial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='aviso_sin_completar_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='domicilio_cargador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='emitido_sin_conexion_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='numero_interno',
            field=models.CharField(blank=True, editable=False, help_text='Número autonumerado por la aplicación (prefijo + contador de ConfiguracionDeca), asignado UNA VEZ al Generar cuando la empresa tiene identificador_preferido="automatico" y no llega con ningún número externo propio. Nunca se reasigna ni se recalcula en una corrección posterior.', max_length=40),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='peso_estimado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='referencia_offline',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='expediciondeca',
            name='sin_remolque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentoorigendeca',
            name='archivo',
            field=models.FileField(max_length=255, upload_to=deca.models._ruta_documento_origen),
        ),
        migrations.AlterField(
            model_name='eventoexpediciondeca',
            name='tipo_evento',
            field=models.CharField(choices=[('creada', 'Expedición creada'), ('documento_subido', 'Documento origen subido'), ('vista_previa', 'Vista previa generada'), ('editada', 'Datos editados'), ('confirmada', 'Confirmada'), ('generada', 'DeCA generado'), ('descarga_publica', 'Descarga pública por QR'), ('anulada', 'Anulada'), ('enviada_email', 'Enviada por email'), ('registrada_papel', 'Registrada como DeCA en papel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expediciondeca',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('generado', 'Generado'), ('anulado', 'Anulado'), ('papel', 'DeCA en papel')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='expediciondeca',
            name='pdf_generado',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=deca.models._ruta_pdf_deca),
        ),
        migrations.AddConstraint(
            model_name='expediciondeca',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia_offline', ''), _negated=True), fields=('referencia_offline',), name='deca_referencia_offline_unica'),
        ),
        migrations.AddField(
            model_name='modificaciondeca',
            name='expedicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modificaciones', to='deca.expediciondeca'),
        ),
        migrations.AddField(
            model_name='modificaciondeca',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modificaciones_deca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lecturacampodeca',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='deca.documentoorigendeca'),
        ),
        migrations.AddField(
            model_name='lecturacampodeca',
            name='expedicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='deca.expediciondeca'),
        ),
        migrations.AddField(
            model_name='lecturacampodeca',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='deca.plantilladocumentodeca'),
        ),
        migrations.AddConstraint(
            model_name='aliasagendadeca',
            constraint=models.UniqueConstraint(fields=('rol', 'texto'), name='deca_alias_unico_por_rol'),
        ),
        migrations.AddIndex(
            model_name='lecturacampodeca',
            index=models.Index(fields=['campo', 'corregido'], name='deca_lectur_campo_418513_idx'),
        ),
    ]
